<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.airlift</groupId>
        <artifactId>airbase</artifactId>
        <version>244</version>
    </parent>

    <groupId>com.brinqa</groupId>
    <artifactId>store-utils</artifactId>
    <version>${revision}</version>
    <packaging>jar</packaging>

    <name>store-utils</name>
    <description>Neo4j Tools for managing indexes.</description>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
            <comments>Note that this license is for the project itself,
                and not for its dependencies. See the included NOTICE.txt
                file for further details.</comments>
        </license>
    </licenses>

    <properties>
        <revision>5.0.x-SNAPSHOT</revision>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!-- plugin versions -->
        <assembly-plugin.version>3.4.2</assembly-plugin.version>
        <spotless.version>2.44.3</spotless.version>

        <air.java.version>17</air.java.version>
        <project.build.targetJdk>17</project.build.targetJdk>

        <!-- skip basic checks -->
        <air.check.skip-basic>true</air.check.skip-basic>

        <!-- checks -->
        <air.check.skip-jacoco>false</air.check.skip-jacoco>
        <air.check.skip-spotbugs>false</air.check.skip-spotbugs>
        <air.check.skip-modernizer>false</air.check.skip-modernizer>

        <!-- skip extended checks -->
        <air.check.skip-pmd>true</air.check.skip-pmd>
        <air.check.skip-license>true</air.check.skip-license>
        <air.check.skip-checkstyle>true</air.check.skip-checkstyle>

        <!-- fail extended checks -->
        <air.check.skip-jacoco>false</air.check.skip-jacoco>
        <air.check.fail-spotbugs>false</air.check.fail-spotbugs>
        <air.check.fail-modernizer>false</air.check.fail-modernizer>

        <!-- javadoc lint -->
        <air.javadoc.lint>-missing</air.javadoc.lint>

        <lombok.version>1.18.36</lombok.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.esotericsoftware</groupId>
            <artifactId>kryo</artifactId>
            <version>5.6.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.18.3</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.18.0</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.4.6-jre</version>
        </dependency>
        <dependency>
            <groupId>info.picocli</groupId>
            <artifactId>picocli</artifactId>
            <version>4.7.6</version>
        </dependency>
        <dependency>
            <groupId>io.reactivex.rxjava3</groupId>
            <artifactId>rxjava</artifactId>
            <version>3.1.10</version>
        </dependency>
        <dependency>
            <groupId>io.vavr</groupId>
            <artifactId>vavr</artifactId>
            <version>0.10.6</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/it.unimi.dsi/fastutil -->
        <dependency>
            <groupId>it.unimi.dsi</groupId>
            <artifactId>fastutil</artifactId>
            <version>8.5.13</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-compress</artifactId>
            <version>1.27.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.17.0</version>
        </dependency>
        <dependency>
            <groupId>org.neo4j</groupId>
            <artifactId>neo4j-cypher-dsl</artifactId>
            <version>2024.5.1</version>
        </dependency>
        <dependency>
            <groupId>org.neo4j.driver</groupId>
            <artifactId>neo4j-java-driver</artifactId>
            <version>5.28.4</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>2.0.12</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.12.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-runner</artifactId>
            <version>1.12.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>neo4j</artifactId>
            <version>1.20.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>maven_central</id>
            <name>Maven Central</name>
            <url>https://repo.maven.apache.org/maven2/</url>
        </repository>
    </repositories>
    <build>
        <plugins>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${spotless.version}</version>
                <configuration>
                    <!-- define a language-specific format -->
                    <java>
                        <importOrder />
                        <removeUnusedImports />
                        <googleJavaFormat />
                    </java>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>compile</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>appassembler-maven-plugin</artifactId>
                <version>1.10</version>
                <configuration>
                    <programs>
                        <program>
                            <name>dump</name>
                            <mainClass>com.brinqa.neo4j.tool.DumpIndex</mainClass>
                        </program>
                        <program>
                            <name>load</name>
                            <mainClass>com.brinqa.neo4j.tool.LoadIndex</mainClass>
                        </program>
                    </programs>
                    <repositoryLayout>flat</repositoryLayout>
                    <repositoryName>lib</repositoryName>
                    <assembleDirectory>${project.build.directory}/store-utils-${project.version}</assembleDirectory>
                    <defaultJvmSettings>
                        <initialMemorySize>8g</initialMemorySize>
                        <maxMemorySize>8g</maxMemorySize>
                    </defaultJvmSettings>
                </configuration>
                <executions>
                    <execution>
                        <id>assemble-standalone-unix</id>
                        <goals>
                            <goal>assemble</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>${assembly-plugin.version}</version>
                <configuration>
                    <descriptors>
                        <descriptor>src/main/assembly/assembly.xml</descriptor>
                    </descriptors>
                    <appendAssemblyId>false</appendAssemblyId>
                    <outputDirectory>${project.build.directory}/distributions</outputDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>make-distribution</id>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <phase>package</phase>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.github.ekryd.sortpom</groupId>
                <artifactId>sortpom-maven-plugin</artifactId>
                <version>3.4.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>sort</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>${project.build.targetJdk}</source>
                    <release>${project.build.targetJdk}</release>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <fork>${air.compiler.fork}</fork>
                    <maxmem>${air.build.jvmsize}</maxmem>
                    <failOnWarning>${air.compiler.fail-warnings}</failOnWarning>
                    <showDeprecation>true</showDeprecation>
                    <showWarnings>true</showWarnings>
                    <parameters>true</parameters>
                    <enablePreview>${air.compiler.enable-preview}</enablePreview>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
