version: '3.3'
services:

  neo4j:
    image: neo4j:3.5.35
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_dbms_memory_pagecache_size: 4G
      NEO4J_dbms_memory_heap_max__size: 2G
      NEO4J_AUTH: "none"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4JLABS_PLUGINS: "[\"apoc\"]"
